githubPhpBoard:
    title: Github PHP dashBoard
    subtitle: Create a home for all your github project
    users:
        - bacardi55:
            - i55WebManager
            - b-55-log
            - dotfiles
