githubPhpBoard:
    title: Bacardi55 project page
    subtitle:
    users:
        - bacardi55:
            - b-55-log
            - i55WebManager
            - jobEscaper55
            - dotfiles
            - gpb
        - lyrixx:
            - Silex-Kitchen-Edition
